// Wrap a .glb as a JavaScript module (base64 string) so the game can load the
// model like any other script: no fetch of .glb/.json/data: URLs, which some
// hosts (e.g. the artifact page) block. Usage: node scripts/gir/glb2js.mjs in.glb out.js
import fs from 'node:fs';
const [inp, out] = process.argv.slice(2);
const b64 = fs.readFileSync(inp).toString('base64');
fs.writeFileSync(out, '// GIR model (binary glTF, base64). Generated by scripts/gir/glb2js.mjs, do not edit.\nexport default \'' + b64 + '\';\n');
console.log(out, fs.statSync(out).size, 'bytes');
