// FIR VALE — hand-placed game locations on top of the real map data
// (./osm.js, generated by scripts/import-map from Overture Maps /
// OpenStreetMap and open elevation data).
//
// Local frame: origin 53.4093 N, 1.4500 W. +X = east, -Z = north (metres).
export const ORIGIN = { lat: 53.4093, lon: -1.45 };
const KX = 111320 * Math.cos(ORIGIN.lat * Math.PI / 180), KZ = 111220;
export const ll = (lat, lon) => [+((lon - ORIGIN.lon) * KX).toFixed(1), +(-(lat - ORIGIN.lat) * KZ).toFixed(1)];

export const PLACES = {
  church: [-105, 165],     // St Cuthbert's, Barnsley Road / Firth Park Road
  miniMart: [140, 44],     // our fictional Mini Mart: a grocer's on Page Hall Road
};
